### ISSUE TITLE
PR cannot be created

### ISSUE THREAD

**Issue by kbiasci** [MistyKuu/bitbucket-for-visual-studio#110]
VS 2017 - 15.9.12
When creating a pull request, after adding the reviewers and clicking on CREATE, the following error message appears:
![image](https://user-images.githubusercontent.com/1813930/59225613-4ae96880-8c25-11e9-990a-9a4cdab3a61f.png)

Clicking on "close source branch" or choosing any reviewer has no incidence.
In total we have 50 branches available.

Thanks for your help!

**Comment by MistyKuu** [comment]
Please attach log file located under %AppData%\GitClientVSExtension\Logs\logs.txt and I'll look further.

**Comment by kbiasci** [comment]
Here you go:
[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/3273769/logs.txt)

**Comment by kbiasci** [comment]
2019-06-11 08:47:32,761 [1] INFO  BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Calling ExecuteTaskAsync. BaseUrl: https://api.bitbucket.org/2.0/ Resource: repositories/bidone/bidone_bidiq/pullrequests
2019-06-11 08:47:33,807 [1] ERROR BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Error in request: {"type": "error", "error": {"fields": {"reviewers": ["Malformed reviewers list"]}, "message": "reviewers: Malformed reviewers list"}}
2019-06-11 08:47:33,814 [1] ERROR GitClientVS.Infrastructure.Extensions.ViewModelsExtensions [(null)] - BitBucket.REST.API.Exceptions.RequestFailedException: reviewers: Malformed reviewers list. Malformed reviewers list
   at BitBucket.REST.API.Wrappers.BitbucketRestClientBase.CheckResponseStatusCode(IRestResponse response)
   at BitBucket.REST.API.Wrappers.BitbucketRestClientBase.<ExecuteTaskAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BitBucket.REST.API.Clients.Standard.PullRequestsClient.<CreatePullRequest>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitClientVS.Services.BitbucketService.<CreatePullRequest>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitClientVS.Infrastructure.ViewModels.CreatePullRequestsViewModel.<CreateNewPullRequest>d__85.MoveNext()

**Comment by MistyKuu** [comment]
I guess this may be related to this: https://community.atlassian.com/t5/Bitbucket-questions/Adding-reviewers-to-pull-requests-via-REST-API/qaq-p/710084
If I get it right, if there is an existing pull request from one branch to another then PUT should be used instead of POST so it will update reviewers. 
Here is the method: https://github.com/MistyKuu/bitbucket-for-visual-studio/blob/ffc51174c99c03048f2695ce87abdab9017a674c/Source/BitBucket.REST.API/Clients/Standard/PullRequestsClient.cs#L249

I'll need to fix this however could you please check if there is existing pull request from test_PR to dev?

**Comment by kbiasci** [comment]
I have created the test_PR branch with the intent to make a single pull request, so no, there was nothing associated with this branch before. The DEV branch is the one being targeted by all the pull requests though (multiple times a day).

**Comment by kbiasci** [comment]
And currently is has one existing PR:
![image](https://user-images.githubusercontent.com/1813930/59227112-a23d0800-8c28-11e9-8f4d-6095610904ec.png)

**Comment by kbiasci** [comment]
Good spotting though! This definitely could be a good lead!

**Comment by MistyKuu** [comment]
The API has changed, I'll fix that soon.

**Comment by kbiasci** [comment]
Legend!
