### ISSUE TITLE
visual studio 2017 repository error

### ISSUE THREAD

**Issue by hideface** [MistyKuu/bitbucket-for-visual-studio#111]
I am getting the following error in visual studio 2017.

Please tell me how to fix it.
Thank you.

2019-06-12 20:21:12,557 [1] INFO  BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Calling ExecuteTaskAsync. BaseUrl: https://api.bitbucket.org/1.0/ Resource: user/repositories

2019-06-12 20:21:12,781 [1] ERROR GitClientVS.Infrastructure.Utils.ExceptionMapper [(null)] - Unknown error: Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[BitBucket.REST.API.Models.Standard.RepositoryV1]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'type', line 1, position 8.
   at BitBucket.REST.API.Wrappers.BitbucketRestClientBase.CheckResponseStatusCode(IRestResponse response)
   at BitBucket.REST.API.Wrappers.BitbucketRestClientBase.<ExecuteTaskAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BitBucket.REST.API.Clients.Standard.RepositoriesClient.<GetUserRepositoriesV1>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitClientVS.Services.BitbucketService.<GetAllRepositories>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitClientVS.Infrastructure.ViewModels.CloneRepositoriesDialogViewModel.<RefreshRepositories>d__51.MoveNext()

**Comment by angelo-loria** [comment]
Also seeing this today. Looks like the plugin is hitting the 1.0 version of the API, when it should be hitting 2.0

**Comment by MistyKuu** [comment]
The reason it doesn't use V2 but v1 is that v2 doesn't list all repositories i.e where you are not owner but you are admin. 
It seems like they make it deprecated:
https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/
I'll need to use V2 again, hopefully they've fixed the above issue.

**Comment by MistyKuu** [comment]
https://github.com/MistyKuu/bitbucket-for-visual-studio/issues/112

**Comment by hideface** [comment]
Thank you. ^^
