### ISSUE TITLE
Empty login screen in VS2019

### ISSUE THREAD

**Issue by ianleeder** [MistyKuu/bitbucket-for-visual-studio#125]
Just setting up a new dev environment, installed VS Community 2019 (v16.2.5), installed ReSharper (Ultimate 2019.2.2), installed GitHub extension (2.9.1.7781) and Bitbucket extension (1.41.2).

I have seen the exception stacktrace as per issue #97.  I didn't do anything specific to fix it, next time I rebooted I could see the Bitbucket extension and login link as expected.  However after clicking Login I'm presented with a blank window:
![Bitbucket login window](https://user-images.githubusercontent.com/8241300/65105235-9fb43080-da17-11e9-967c-b3b62dc158f8.png)
If I move the mouse cursor around, it changes to indicate that the input fields actually are there, I just can't see them.

Issue still persists after restart VS or reboot.

I checked log file in `%appdata%\GitClientVSExtension\Logs`, this is the contents:

	2019-09-18 12:47:33,354 [1] INFO  GitClientVS.VisualStudio.UI.GitClientVSPackage [(null)] - Initialized GitClientVsPackage Extension
	2019-09-18 13:15:24,362 [1] ERROR GitClientVS.VisualStudio.UI.GitClientVSPackage [(null)] - Unhandled Dispatcher GitClientVsExtensions Error
	System.Exception: The component 'MahApps.Metro.Controls.GlowWindow' does not have a resource identified by the URI '/MahApps.Metro;component/controls/glowwindow.xaml'.
	   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
	   at MahApps.Metro.Controls.GlowWindow.InitializeComponent()
	   at MahApps.Metro.Controls.GlowWindow..ctor(Window owner, GlowDirection direction)
	   at MahApps.Metro.Behaviours.GlowWindowBehavior.AssociatedObjectOnLoaded(Object sender, RoutedEventArgs routedEventArgs)
	   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
	   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
	   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
	   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
	   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
	   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
	   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
	   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
	   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
	   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
	   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
	   at System.Windows.Interop.HwndTarget.OnResize()
	   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
	   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by SchreinerK** [comment]
same issue on me. 
after clearing ComponentModelCache, no exception, but empty login.
Reinstalling the extension seems to fix it.

**Comment by mac671** [comment]
I have also experienced this. What worked for me was:
1. Disable extension - Reset VS
2. Enable extension - Reset VS

**Comment by ianleeder** [comment]
I was trying to leave this in a broken state in case I could assist with debugging, but since it's gone a month without response I've given up.
I tried Disable/Reset/Enable/Reset, but it didn't work for me.  I had to uninstall then reinstall to get it working properly.

**Comment by MistyKuu** [comment]
Mahapps causes a lot of issues in this plugin. I'm afraid I'll not be able to help with this, I must have stopped development of this project, hower I'm happy to approve any PRs with fixes.

**Comment by SparkStefan** [comment]
It seems to me like this could be a rendering problem. Actually updating the Nvidia graphics drivers solved the problem for me.
