### ISSUE TITLE
Visual Studio 2017 crash on opening pull request

### ISSUE THREAD

**Issue by aniltrimbake** [MistyKuu/bitbucket-for-visual-studio#128]
we are testing some features of bitbucket plugin into visual studio 2017 version and found below error while opening pull request. is this known issue ? any fix available ? please suggest

Error:
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at GitClientVS.UI.Converters.UrlToImageSourceConverter..cctor()

Exception Info: System.TypeInitializationException
   at GitClientVS.UI.Converters.UrlToImageSourceConverter..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadComponent(System.Object, System.Uri)
   at GitClientVS.UI.Views.PullRequestDetailView.InitializeComponent()
   at GitClientVS.UI.Views.PullRequestDetailView..ctor(GitClientVS.Contracts.Interfaces.ViewModels.IPullRequestsDetailViewModel)

Exception Info: Microsoft.VisualStudio.Composition.CompositionFailedException
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory+RuntimeExportProvider+RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider+PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider+PartLifecycleTracker.MoveNext(PartLifecycleState)
   at Microsoft.VisualStudio.Composition.ExportProvider+PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider+<>c__DisplayClass53_0.<CreateExport>b__0()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CreateValue()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].LazyInitValue()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Value()
   at Microsoft.VisualStudio.Composition.NetFxAdapters+MefV1ExportProvider+<>c__DisplayClass12_0.<UnwrapExport>b__1()
   at System.ComponentModel.Composition.Primitives.Export.GetExportedValueCore()
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.ComponentModel.Composition.Primitives.Export)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValuesCore[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String)
   at GitClientVS.VisualStudio.UI.AppServiceProvider.GetServiceFromExportProvider(System.Type)
   at GitClientVS.VisualStudio.UI.AppServiceProvider.GetService(System.Type)
   at GitClientVS.VisualStudio.UI.AppServiceProvider.GetService[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]()
   at GitClientVS.VisualStudio.UI.Services.PageNavigationService`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Navigate[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object)
   at GitClientVS.Infrastructure.ViewModels.PullRequestsMainViewModel.<InitializeCommands>b__59_2(GitClientVS.Contracts.Models.GitClientModels.GitPullRequest)
   at ReactiveUI.ReactiveCommand+<>c__DisplayClass2_1`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Create>b__1(System.IObserver`1<System.Reactive.Unit>)
   at System.Reactive.AnonymousObservable`1[[System.Reactive.Unit, System.Reactive.Core, Version=2.2.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].SubscribeCore(System.IObserver`1<System.Reactive.Unit>)
   at System.Reactive.ObservableBase`1[[System.Reactive.Unit, System.Reactive.Core, Version=2.2.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Subscribe(System.IObserver`1<System.Reactive.Unit>)

Exception Info: ReactiveUI.UnhandledErrorException
   at ReactiveUI.RxApp+<>c__DisplayClass0_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(System.Reactive.Concurrency.IScheduler, System.Action)
   at System.Reactive.Concurrency.DispatcherScheduler+<>c__DisplayClass1`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by MistyKuu** [comment]
You'd need to debug it yourself. The error is thrown in this constructor but I've no idea where file not found would be raised.
https://github.com/MistyKuu/bitbucket-for-visual-studio/blob/5e59c70553d4a9cb415d62f75897e307bf968a54/Source/GitClientVS.UI/Converters/UrlToImageSourceConverter.cs#L43

**Comment by aniltrimbake** [comment]
Thanks Mistykuu. I was able to debug and found required .net framework was not installed on my workstation, after install .net framework 4.7.2 i was able to open Pull Request.
