### ISSUE TITLE
Crashes on Visual Studio after i try to login VS2015

### ISSUE THREAD

**Issue by ZabalaMelendez** [MistyKuu/bitbucket-for-visual-studio#3]
When i try to login v2015 crashes  and restart VS15. 
This its my log file.
2017-05-07 20:28:34,457 [1] INFO  GitClientVS.VisualStudio.UI.GitClientVSPackage [(null)] - Initialized GitClientVsPackage Extension
2017-05-07 20:32:46,496 [1] INFO  BitBucket.REST.API.BitbucketClientFactory [(null)] - Calling CreateStandardBitBucketClient.
2017-05-07 20:32:46,543 [1] INFO  BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Calling ExecuteTaskAsync. BaseUrl: https://api.bitbucket.org/2.0/ Resource: user
2017-05-07 20:32:49,454 [1] ERROR GitClientVS.Infrastructure.Extensions.ViewModelsExtensions [(null)] - BitBucket.REST.API.Exceptions.AuthorizationException: Unauthorized
   at BitBucket.REST.API.Wrappers.BitbucketRestClientBase.CheckResponseStatusCode(IRestResponse response)
   at BitBucket.REST.API.Wrappers.BitbucketRestClientBase.<ExecuteTaskAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BitBucket.REST.API.Clients.Standard.UserClient.<GetUser>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BitBucket.REST.API.BitbucketClientFactory.<CreateStandardBitBucketClient>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitClientVS.Services.BitbucketService.<CreateBitbucketClient>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitClientVS.Services.BitbucketService.<LoginAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitClientVS.Infrastructure.ViewModels.LoginDialogViewModel.<Connect>d__23.MoveNext()
[logs.txt](https://github.com/MistyKuu/bitbucketvsextension/files/1016608/logs.txt)

**Comment by MistyKuu** [comment]
Hey,
thank you for submitting the first issue :) 
Just to let you know the part of log you copied is from 2017-05-07, you should've copied the bottom part.
Anyway, in this particular case it looks all good from the logs point of view. There are some exceptions thrown and caught in viewmodel which shouldn't crash VS.
I think we should look at ActivityLog.xml file.
Could you start VS with /log flag, then reproduce the crash and check the content of ActivityLog.xml file?
More info how to generate and find it here: https://msdn.microsoft.com/pl-pl/library/ms241272.aspx?f=255&MSPPError=-2147217396

**Comment by MistyKuu** [comment]
The same issue: #5
