### ISSUE TITLE
Unable to install -> Illegal characters in path

### ISSUE THREAD

**Issue by QuintonC** [MistyKuu/bitbucket-for-visual-studio#38]
Hello,

We are having issues getting one of our developers set up with this plugin for VS2015.

Here is the application path for VS2015: `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe`

Here is a small excerpt from the log (I have also included the log file below) :

```
11/14/2017 3:13:08 PM - Found installed product - Microsoft Visual Studio Professional 2015
11/14/2017 3:13:09 PM - System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionSettingsStoreList.ReadEntriesFromSettingsStore(SettingsStore store)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionSettingsStoreList.get_ListEntries()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InitializeEnabledExtensions(CachedInstalledExtensionList cachedExtensionsList, IEnumerable`1 enabledExtensions)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InitializeList(CachedInstalledExtensionList cachedExtensionsList, IEnumerable`1 enabledExtensions, Boolean safeMode, Boolean isSdkList, Int64 lastExtensionsChangedTimestamp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstalledExtensionListData.<>c__DisplayClass16_0.<CreateExtensionListData>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.PartitionedInstalledExtensionList.<>c.<BeginBatch>b__18_0(InstalledExtensionListData listData)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.PartitionedInstalledExtensionList.BeginBatch()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.PartitionedInstalledExtensionList.TryGetValue(String identifier, IInstalledExtension& result)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.TryGetInstalledExtension(String identifier, IInstalledExtension& result)
   at VSIXInstaller.App.GetExtensionManagerForApplicableSKU(SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs, Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
---> (Inner Exception #0) System.ArgumentException: Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionSettingsStoreList.ReadEntriesFromSettingsStore(SettingsStore store)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionSettingsStoreList.get_ListEntries()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InitializeEnabledExtensions(CachedInstalledExtensionList cachedExtensionsList, IEnumerable`1 enabledExtensions)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InitializeList(CachedInstalledExtensionList cachedExtensionsList, IEnumerable`1 enabledExtensions, Boolean safeMode, Boolean isSdkList, Int64 lastExtensionsChangedTimestamp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstalledExtensionListData.<>c__DisplayClass16_0.<CreateExtensionListData>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

[Log File](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/1472428/VSIXInstaller_7178d154-ddef-4a0e-9722-f9bb489b7c92.log)

Best,
Quinton Chester

**Comment by MistyKuu** [comment]
Hi,
can he install other extensions or it's just this one?

**Comment by QuintonC** [comment]
Hey,

You actually responded RIGHT as we resolved the issue.

We found that there was an issue within his registry. There was a random '/?/' in the path for some odd reason. But we fixed it and he was able to get it installed.

Thank you for getting back to us!
