### ISSUE TITLE
Visual Studio bug with styles throws unhandled exception

### ISSUE THREAD

**Issue by MistyKuu** [MistyKuu/bitbucket-for-visual-studio#53]
Hi Misty, I have latest visual studio 15.6.2 (professional) 
I just installed the extension. When I click login, this gets written to %appdata%\GitClientVSExtension\Logs

2018-03-21 12:22:46,214 [1] INFO GitClientVS.VisualStudio.UI.GitClientVSPackage [(null)] - Initialized GitClientVsPackage Extension
2018-03-21 12:23:08,834 [1] ERROR GitClientVS.VisualStudio.UI.GitClientVSPackage [(null)] - Unhandled Dispatcher GitClientVsExtensions Error
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "GitClientVS.UI.Views.LoginDialogView". ---> System.Windows.Markup.XamlParseException: Initialization of 'GitClientVS.UI.Styles.SharedResourceDictionary' threw an exception. ---> System.InvalidOperationException: 'MetroWindow' TargetType does not match type of element 'LoginDialogView'.
at System.Windows.Style.CheckTargetType(Object element)
at System.Windows.StyleHelper.UpdateStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle, Style& styleCache)
at System.Windows.FrameworkElement.OnStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
at

https://github.com/MistyKuu/bitbucket-for-visual-studio/issues/37

Possible fix:

https://github.com/MahApps/MahApps.Metro/issues/1315

**Comment by MistyKuu** [comment]
Released in 1.37.2
