### ISSUE TITLE
Json Error in VS 2017

### ISSUE THREAD

**Issue by skywqr** [MistyKuu/bitbucket-for-visual-studio#67]
I see the following error while creating the pull request and merging the code.
Please help me resolve this ASAP.

2018-06-24 12:18:40,927 [1] INFO BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Calling ExecuteTaskAsync. BaseUrl: http://axx@bbserver:7990/rest/api/1.0 Resource: projects/rl/repos/eftest/pull-requests
2018-06-24 12:18:41,064 [47] ERROR BitBucket.REST.API.Serializers.NewtonsoftJsonSerializer [(null)] - Couldn't deserialize json: {"errors":[{"context":null,"message":"Branch "master" is already up-to-date with branch "ANFB6" in repository "eftest".","exceptionName":"com.atlassian.bitbucket.pull.EmptyPullRequestException"}]}. Error: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '', line 1, position 1.
at Newtonsoft.Json.JsonTextReader.ReadAsBoolean()
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
at BitBucket.REST.API.Serializers.NewtonsoftJsonSerializer.Deserialize[T](String json)
2018-06-24 12:18:41,064 [1] ERROR BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Error content: {"errors":[{"context":null,"message":"Branch "master" is already up-to-date with branch "ANFB6" in repository "eftest".","exceptionName":"com.atlassian.bitbucket.pull.EmptyPullRequestException"}]}
2018-06-24 12:18:41,066 [1] ERROR GitClientVS.Infrastructure.Extensions.ViewModelsExtensions [(null)] - Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '', line 1, position 1.
at BitBucket.REST.API.Wrappers.BitbucketRestClientBase.CheckResponseStatusCode(IRestResponse response)
at BitBucket.REST.API.Wrappers.BitbucketRestClientBase.d__91.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at BitBucket.REST.API.Wrappers.BitbucketRestClientBase.<ExecuteTaskAsync>d__10.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at BitBucket.REST.API.Clients.Enterprise.EnterprisePullRequestsClient.<CreatePullRequest>d__22.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at GitClientVS.Services.BitbucketService.<CreatePullRequest>d__39.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at GitClientVS.Infrastructure.ViewModels.CreatePullRequestsViewModel.<CreateNewPullRequest>d__86.MoveNext() 2018-06-24 12:18:41,067 [1] ERROR GitClientVS.Infrastructure.Utils.ExceptionMapper [(null)] - Unknown error: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '', line 1, position 1. at BitBucket.REST.API.Wrappers.BitbucketRestClientBase.CheckResponseStatusCode(IRestResponse response) at BitBucket.REST.API.Wrappers.BitbucketRestClientBase.<ExecuteTaskAsync>d__91.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at BitBucket.REST.API.Wrappers.BitbucketRestClientBase.d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at BitBucket.REST.API.Clients.Enterprise.EnterprisePullRequestsClient.d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at GitClientVS.Services.BitbucketService.d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at GitClientVS.Infrastructure.ViewModels.CreatePullRequestsViewModel.d__86.MoveNext()
2018-06-24 12:27:13,636 [1] INFO GitClientVS.Services.BitbucketClientFactory [(null)] - Calling CreateEnterpriseBitBucketClient. Host: http://axx@bbserver:7990/

**Comment by MistyKuu** [comment]
There is already an issue regarding this:
https://github.com/MistyKuu/bitbucket-for-visual-studio/issues/63
