### ISSUE TITLE
Pull request throws 'invalid page' error (same as #80)

### ISSUE THREAD

**Issue by mgwillett** [MistyKuu/bitbucket-for-visual-studio#93]
This appears to be duplicate of closed issue: https://github.com/MistyKuu/bitbucket-for-visual-studio/issues/80

I'm running VS2017 15.9.7 with Bitbucket Extension 1.40.1; when opening dialog to create new pull request the same 'invalid page' error is thrown and displayed:

![image](https://user-images.githubusercontent.com/47605385/52815414-a5562c00-306c-11e9-9501-7abe2bf9972f.png)

Here is logs.txt from AppData\Roaming\GitClientVSExtension\Logs folder for this session (path tweaked for anonymity):

2019-02-14 15:18:21,192 [1] INFO  GitClientVS.Services.BitbucketClientFactory [(null)] - Calling CreateStandardBitBucketClient.
2019-02-14 15:18:21,222 [1] INFO  BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Calling ExecuteTaskAsync. BaseUrl: https://api.bitbucket.org/2.0/ Resource: user
2019-02-14 15:18:21,409 [1] INFO  GitClientVS.VisualStudio.UI.GitClientVSPackage [(null)] - Initialized GitClientVsPackage Extension
2019-02-14 15:19:01,094 [1] INFO  BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Calling ExecuteTaskAsync. BaseUrl: https://bitbucket.org/!api/internal/ Resource: repositories/XXXXwebservices/XXXX/pr-authors/
2019-02-14 15:19:01,624 [1] INFO  BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Calling ExecuteTaskAsync. BaseUrl: https://api.bitbucket.org/2.0/ Resource: repositories/XXXXwebservices/XXXX/pullrequests
2019-02-14 15:19:06,235 [1] INFO  BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Calling ExecuteTaskAsync. BaseUrl: https://api.bitbucket.org/2.0/ Resource: repositories/XXXXwebservices/XXXX/refs/branches
2019-02-14 15:19:07,252 [1] INFO  BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Calling ExecuteTaskAsync. BaseUrl: https://api.bitbucket.org/2.0/ Resource: repositories/XXXXwebservices/XXXX/refs/branches
2019-02-14 15:19:07,942 [1] ERROR BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Error in request: {"type": "error", "error": {"message": "Invalid page"}}
2019-02-14 15:19:07,959 [1] ERROR GitClientVS.Infrastructure.Extensions.ViewModelsExtensions [(null)] - BitBucket.REST.API.Exceptions.RequestFailedException: Invalid page
   at BitBucket.REST.API.Wrappers.BitbucketRestClientBase.CheckResponseStatusCode(IRestResponse response)
   at BitBucket.REST.API.Wrappers.BitbucketRestClientBase.<ExecuteTaskAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BitBucket.REST.API.Wrappers.BitbucketRestClient.<GetAllPages>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BitBucket.REST.API.Clients.Standard.RepositoriesClient.<GetBranches>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitClientVS.Services.BitbucketService.<GetBranches>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitClientVS.Infrastructure.ViewModels.CreatePullRequestsViewModel.<LoadBranches>d__86.MoveNext()

**Comment by MistyKuu** [comment]
Fixed by https://github.com/MistyKuu/bitbucket-for-visual-studio/commit/03d3385ee6125fd149560c24aeda10da8168410a in 1.40.2. Please reopen if issue still exists.
