### ISSUE TITLE
Plugin crashes with error Could not load assembly System.Net.Http

### ISSUE THREAD

**Issue by ryan-kelly-tylertech** [MistyKuu/bitbucket-for-visual-studio#98]
I am getting this error when attempting to do almost anything in the plugin.  The most straightforward thing is to try to view a pull request details:

2019-03-22 13:28:05,245 [1] ERROR GitClientVS.Infrastructure.Utils.ExceptionMapper [(null)] - Unknown error: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at GitClientVS.UI.Converters.UrlToImageSourceConverter.GetImage(String url)
   at GitClientVS.UI.Converters.UrlToImageSourceConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.ScheduleTransfer(Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at MS.Internal.Data.PropertyPathWorker.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   at ReactiveUI.ReactiveObject.ReactiveUI.IReactiveObject.RaisePropertyChanged(PropertyChangedEventArgs args)
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.raisePropertyChanged(String propertyName)
   at ReactiveUI.IReactiveObjectExtensions.raisePropertyChanged[TSender](TSender This, String propertyName)
   at ReactiveUI.IReactiveObjectExtensions.RaiseAndSetIfChanged[TObj,TRet](TObj This, TRet& backingField, TRet newValue, String propertyName)
   at GitClientVS.Infrastructure.ViewModels.PullRequestsDetailViewModel.<GetPullRequestInfo>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitClientVS.Infrastructure.ViewModels.PullRequestsDetailViewModel.<LoadPullRequestData>d__60.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

The error started after reinstalling Visual Studio and the Plugin (after upgrading windows).

**Comment by ryan-kelly-tylertech** [comment]
This error is occurring in the plugin window when i turn on logging.  If i don't turn on logging, the plugin just crashes instead.
![error](https://user-images.githubusercontent.com/41805403/54926791-029c9300-4edf-11e9-9144-7c0f66f04a42.png)

**Comment by MistyKuu** [comment]
Please try 1.40.3, I've replaced System.Net.Http.dll with RestSharp and I've removed direct reference to it. Let me know if it helped.

**Comment by ryan-kelly-tylertech** [comment]
Seems to have fixed the problem.  Perfect!
